### PR TITLE
fix list index out of range error

### PR DESCRIPTION
**Pull request by diether1**
Include validation on **inspect.getsourcelines(f)[1]** to fix list index out of range error

### CODE REVIEW

**Comment by canassa** [comment]
Thanks!

**Comment by canassa** [comment]
One question. What the `getsourcelines()` methods returns for you so that you need to check for its length?

**Comment by canassa** [comment]
Please update to flask-trace 0.0.2. It already contains your PR.

**Comment by diether1** [comment]
Canassa, 
for some reason , in some cases it does not return the object, generating the error. I could not simulate the error here =S
Talking to the Rafael Martins he told me to do this check directly into flask_trace lib.
Thanks!

**Comment by diether1** [comment]
See this bug report 
http://bugs.python.org/issue17526

**Pull request merged**
